title: 'Infocomm Media Development Authority'
description: Description
url: ""
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
kramdown:
    parse_block_html: true
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
collections:
    innovate:
        output: true
    experience:
        output: false
    media:
        output: true
    highlights:
        output: true
favicon: /images/SGD-logo.png
google-analytics: UA-79861556-1
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
